spring:
  config:
    activate:
      on-profile: local

  datasource:
#    url: jdbc:h2:mem:ucamp;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: SCOTT
    password: TIGER

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080


app:
  frontend-origin: "http://localhost:3000"
  jwt:
    issuer: "api.example.com"
    access-exp-minutes: 15
    refresh-exp-days: 7
    secret: "${JWT_SECRET}"
  cookie:
    refresh:
      name: "refresh_token"
      domain: "localhost"
      path: "/auth"
      secure: false
      same-site: "Lax"
  kakao:
    client-id: "${KAKAO_CLIENT_ID}"
    client-secret: "${KAKAO_CLIENT_SECRET}"
    redirect-uri: "${KAKAO_REDIRECT_URI:http://localhost:8080/auth/kakao/callback}"