spring:
  application:
    name: ucamp_project_server

  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  security:
    user:
      name: user
      password: password

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

# 카카오 고정 URI
app:
  kakao:
    token-uri: "https://kauth.kakao.com/oauth/token"
    userinfo-uri: "https://kapi.kakao.com/v2/user/me"