spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080


#app:
#  frontend-origin: "https://yourdomain.com"
#  jwt:
#    issuer: "api.yourdomain.com"
#    access-exp-minutes: 15
#    refresh-exp-days: 7
#    secret: "${JWT_SECRET}"
#  cookie:
#    refresh:
#      name: "refresh_token"
#      domain: "api.yourdomain.com"
#      path: "/auth"
#      secure: true  # 👈 운영환경에서는 true
#      same-site: "Strict"
#  kakao:
#    client-id: "${KAKAO_CLIENT_ID}"
#    client-secret: "${KAKAO_CLIENT_SECRET}"
#    redirect-uri: "https://api.yourdomain.com/auth/kakao/callback"