package com.ucamp.project.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.ColumnDefault;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "CERTIFICATE")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Certificate {
//    cert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//    nickname VARCHAR2(10) NOT NULL,
//    cert_status VARCHAR2(10) DEFAULT 'PENDING' CHECK (cert_status IN ('PENDING', 'APPROVED', 'REJECTED')),
//    cert_req_date DATE, -- 요청날짜
//    cert_file_url VARCHAR2(255) NOT NULL,
//    cert_trmt_date DATE, -- 요청 처리 날짜
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="cert_id")
    private Long certId;

    @ManyToOne
    @JoinColumn(name = "nickname")
    private User user;

    @Column(name = "cert_status")
    private String certStatus;

    @Column(name = "cert_req_date")
    private LocalDateTime certReqDate;

    @Column(name = "cert_file_url", nullable = false)
    private String certFileUrl;

    @Column(name = "cert_trmt_date")
    private LocalDateTime certTrmtDate;
}
